server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/world
    username: root
    password: rootpass123
  application:
    name: spring-boot

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health    
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
  api-docs:
    path: /api-docs 
    
logging:
  level:
    root: INFO 
    com.example.spring_boot.service : DEBUG